from __future__ import annotations

from dataclasses import dataclass

from lebihsini_greenproof.contracts import (
    DemandRequest,
    EquipmentResourcePassport,
    MaterialResourcePassport,
    RiskCategory,
    VerificationStatus,
)


@dataclass(slots=True)
class DemoDataset:
    demand: DemandRequest
    material_resources: list[MaterialResourcePassport]
    equipment_resources: list[EquipmentResourcePassport]
    commercial_equipment_rental_daily_myr: float
    supplier_unit_price_myr: float
    supplier_delivery_cost_myr: float
    supplier_delivery_distance_km: float
    disposal_or_storage_cost_myr: float
    disposal_or_storage_carbon_kgco2e: float
    inspection_cost_per_amber_resource_myr: float
    additional_handling_cost_myr: float
    platform_fee_myr: float
    expected_delay_cost_myr: float


def load_demo_dataset() -> DemoDataset:
    demand = DemandRequest(
        demand_id="demand-site-c-001",
        requesting_site_id="site-c",
        material_category="porcelain_tile",
        product_code="PG-600-GREY",
        colour="grey",
        dimension_mm_width=600,
        dimension_mm_height=600,
        quantity_units=500,
        deadline_at="2026-06-21T11:00:00+08:00",
        equipment_category="tile_cutter",
        equipment_duration_days=2,
        maximum_distance_km=25.0,
        maximum_risk=RiskCategory.AMBER,
        extraction_confidence=0.91,
        input_language="ms-MY",
        source_type="voice_note",
        notes="Demo demand extracted from a Bahasa voice note.",
    )

    material_resources = [
        MaterialResourcePassport(
            resource_id="mat-site-a-tiles",
            site_id="site-a",
            site_name="Site A - Puchong Utama",
            category="porcelain_tile",
            brand="DemoCeram",
            product_code="PG-600-GREY",
            dimension_mm_width=600,
            dimension_mm_height=600,
            colour="grey",
            quantity_units=300,
            transfer_price_myr_per_unit=3.20,
            packaging_status="sealed_boxes",
            storage_condition="indoor_dry",
            rescue_deadline_at="2026-06-22T18:00:00+08:00",
            available_from_at="2026-06-20T08:00:00+08:00",
            collection_window_start_at="2026-06-20T08:00:00+08:00",
            collection_window_end_at="2026-06-21T09:30:00+08:00",
            distance_to_site_km=11.0,
            travel_time_to_site_minutes=40,
            transport_rate_myr_per_km=4.0,
            vehicle_factor_kgco2e_per_km=0.27,
            embodied_carbon_kgco2e_per_unit=1.80,
            confidence=0.97,
            risk_category=RiskCategory.GREEN,
            verification_status=VerificationStatus.VERIFIED,
            inspection_required=False,
            has_required_documentation=True,
            evidence_notes=["Correct product code visible.", "Sealed packaging confirmed."],
        ),
        MaterialResourcePassport(
            resource_id="mat-site-b-tiles",
            site_id="site-b",
            site_name="Site B - Bandar Puteri",
            category="porcelain_tile",
            brand="DemoCeram",
            product_code="PG-600-GREY",
            dimension_mm_width=600,
            dimension_mm_height=600,
            colour="grey",
            quantity_units=130,
            transfer_price_myr_per_unit=3.00,
            packaging_status="opened_boxes",
            storage_condition="indoor_dry",
            rescue_deadline_at="2026-06-22T18:00:00+08:00",
            available_from_at="2026-06-21T09:00:00+08:00",
            collection_window_start_at="2026-06-21T09:00:00+08:00",
            collection_window_end_at="2026-06-21T10:00:00+08:00",
            distance_to_site_km=17.0,
            travel_time_to_site_minutes=55,
            transport_rate_myr_per_km=4.0,
            vehicle_factor_kgco2e_per_km=0.27,
            embodied_carbon_kgco2e_per_unit=1.80,
            confidence=0.84,
            risk_category=RiskCategory.AMBER,
            verification_status=VerificationStatus.PARTIAL,
            inspection_required=True,
            has_required_documentation=True,
            evidence_notes=["Same dimensions and product code.", "Different production batch.", "Buyer inspection required."],
        ),
        MaterialResourcePassport(
            resource_id="mat-site-e-tiles",
            site_id="site-e",
            site_name="Site E - Kinrara",
            category="porcelain_tile",
            brand="Unknown",
            product_code="UNKNOWN",
            dimension_mm_width=600,
            dimension_mm_height=600,
            colour="grey",
            quantity_units=100,
            transfer_price_myr_per_unit=2.50,
            packaging_status="loose_stacks",
            storage_condition="outdoor_exposed",
            rescue_deadline_at="2026-06-22T18:00:00+08:00",
            available_from_at="2026-06-20T08:00:00+08:00",
            collection_window_start_at="2026-06-20T08:00:00+08:00",
            collection_window_end_at="2026-06-21T08:30:00+08:00",
            distance_to_site_km=14.0,
            travel_time_to_site_minutes=45,
            transport_rate_myr_per_km=4.0,
            vehicle_factor_kgco2e_per_km=0.27,
            embodied_carbon_kgco2e_per_unit=1.80,
            confidence=0.41,
            risk_category=RiskCategory.RED,
            verification_status=VerificationStatus.UNVERIFIED,
            inspection_required=True,
            has_required_documentation=False,
            evidence_notes=["Product label unreadable.", "Stored outdoors.", "Specification cannot be confidently confirmed."],
        ),
        MaterialResourcePassport(
            resource_id="mat-site-g-wrong-size",
            site_id="site-g",
            site_name="Site G - Shah Alam",
            category="porcelain_tile",
            brand="DemoCeram",
            product_code="PG-800-GREY",
            dimension_mm_width=800,
            dimension_mm_height=800,
            colour="grey",
            quantity_units=120,
            transfer_price_myr_per_unit=3.40,
            packaging_status="sealed_boxes",
            storage_condition="indoor_dry",
            rescue_deadline_at="2026-06-22T18:00:00+08:00",
            available_from_at="2026-06-20T08:00:00+08:00",
            collection_window_start_at="2026-06-20T08:00:00+08:00",
            collection_window_end_at="2026-06-21T08:00:00+08:00",
            distance_to_site_km=20.0,
            travel_time_to_site_minutes=65,
            transport_rate_myr_per_km=4.0,
            vehicle_factor_kgco2e_per_km=0.27,
            embodied_carbon_kgco2e_per_unit=2.10,
            confidence=0.95,
            risk_category=RiskCategory.GREEN,
            verification_status=VerificationStatus.VERIFIED,
            inspection_required=False,
            has_required_documentation=True,
            evidence_notes=["Included as a deterministic mismatch test resource."],
        ),
    ]

    equipment_resources = [
        EquipmentResourcePassport(
            resource_id="eq-site-d-cutter",
            site_id="site-d",
            site_name="Site D - Subang Jaya",
            category="tile_cutter",
            brand_model="Hilti DC-600 Demo",
            owner="Site D",
            availability_start_at="2026-06-20T08:00:00+08:00",
            availability_end_at="2026-06-23T18:00:00+08:00",
            collection_window_start_at="2026-06-21T08:00:00+08:00",
            collection_window_end_at="2026-06-21T09:00:00+08:00",
            rental_rate_myr_per_day=60.0,
            commercial_rental_rate_myr_per_day=120.0,
            distance_to_site_km=9.0,
            travel_time_to_site_minutes=30,
            transport_rate_myr_per_km=4.0,
            vehicle_factor_kgco2e_per_km=0.27,
            maintenance_record_present=True,
            maintenance_confidence=0.92,
            operator_required=False,
            risk_category=RiskCategory.GREEN,
            verification_status=VerificationStatus.VERIFIED,
            evidence_notes=["Maintenance record present.", "Available for three days."],
        ),
        EquipmentResourcePassport(
            resource_id="eq-site-h-unavailable",
            site_id="site-h",
            site_name="Site H - Klang",
            category="tile_cutter",
            brand_model="Demo Cutter Backup",
            owner="Site H",
            availability_start_at="2026-06-22T08:00:00+08:00",
            availability_end_at="2026-06-22T18:00:00+08:00",
            collection_window_start_at="2026-06-22T08:00:00+08:00",
            collection_window_end_at="2026-06-22T09:00:00+08:00",
            rental_rate_myr_per_day=55.0,
            commercial_rental_rate_myr_per_day=120.0,
            distance_to_site_km=28.0,
            travel_time_to_site_minutes=70,
            transport_rate_myr_per_km=4.0,
            vehicle_factor_kgco2e_per_km=0.27,
            maintenance_record_present=True,
            maintenance_confidence=0.90,
            operator_required=False,
            risk_category=RiskCategory.GREEN,
            verification_status=VerificationStatus.VERIFIED,
            evidence_notes=["Included as an unavailable fallback example."],
        ),
    ]

    return DemoDataset(
        demand=demand,
        material_resources=material_resources,
        equipment_resources=equipment_resources,
        commercial_equipment_rental_daily_myr=120.0,
        supplier_unit_price_myr=4.60,
        supplier_delivery_cost_myr=90.0,
        supplier_delivery_distance_km=18.0,
        disposal_or_storage_cost_myr=20.0,
        disposal_or_storage_carbon_kgco2e=8.0,
        inspection_cost_per_amber_resource_myr=25.0,
        additional_handling_cost_myr=30.0,
        platform_fee_myr=15.0,
        expected_delay_cost_myr=0.0,
    )
