EXPLANATION_TEXT = {
    "resource_selected": "Selected because it matches the requested specification and remains feasible within the stated deadline.",
    "resource_excluded_unverified_spec": "Excluded from automatic recommendation because the product specification could not be verified.",
    "inspection_required": "Manual inspection required before this resource can be approved.",
    "deadline_infeasible": "Reuse was not recommended because the delivery deadline could not be met.",
    "documentation_missing": "Excluded from automatic recommendation because required documentation was absent.",
    "supplier_fallback_required": "Supplier fallback added to fulfil the remaining quantity.",
    "supplier_selected": "Supplier F filled the remaining quantity after eligible reuse sources were exhausted.",
    "negative_net_carbon_benefit": "Reuse was not recommended because the estimated transport impact outweighed the avoided material carbon.",
    "partial_reuse_recommended": "Partial reuse recommended because it reduced new purchasing while keeping the plan feasible.",
    "normal_procurement_recommended": "Normal procurement recommended because reuse did not satisfy the current operational constraints.",
    "commercial_equipment_fallback": "Commercial equipment fallback selected to preserve deadline feasibility.",
    "deadline_feasible": "Collection and delivery remain feasible within the current deadline.",
    "available_too_late": "Excluded because the resource becomes available too late for the selected deadline.",
    "collection_window_missed": "Excluded because the usable collection window is missed before delivery can be completed.",
    "travel_deadline_missed": "Excluded because collection and travel cannot finish before the selected deadline.",
    "distance_exceeded": "Excluded because the source exceeds the maximum allowed distance.",
    "risk_exceeded": "Excluded because the resource risk exceeds the allowed tolerance.",
    "verification_insufficient": "Excluded from automatic recommendation because the verification status is insufficient for accountable matching.",
    "maintenance_insufficient": "Excluded because maintenance evidence does not meet the minimum threshold.",
    "equipment_duration_infeasible": "Excluded because the equipment is not available for the full requested duration.",
    "operator_requirement_unmet": "Excluded because the equipment requires an operator arrangement that is not represented in the current MVP flow.",
    "urgency_plan_changed": "Urgency changed the plan because one or more reuse sources could no longer complete collection and delivery in time.",
    "low_confidence_ai_extraction": "Human confirmation required because one or more extracted fields had limited confidence.",
    "human_confirmation_required": "The user must confirm extracted fields before final recommendation approval.",
    "estimated_assumptions": "Estimated using stated cost and carbon assumptions.",
    "site_e_uncertainty": "Excluded from automatic recommendation because the product label was unreadable and the condition could not be sufficiently verified.",
}
